---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/2/24 21:07
---

function GetIsMarineUnit(entity)
    return entity and HasMixin(entity, "Team")
end
function GetIsAlienUnit(entity)
    return false
end